<?php require_once('template/header.phtml'); ?>

    <div id="chat">
        <div id="otherUser">
            <h3><?php echo $view->otherUser ?></h3>
        </div>
        <div id="messages">



        </div>
        <div class="input-group">
            <textarea class="form-control" aria-label="With textarea" id="chatMessage"></textarea>
            <input type="hidden" id="receiverId" value="<?php echo $view->otherUser ?>">
            <input type="hidden" id="senderId" value="<?php echo $_SESSION['username']?>">
        </div>
        <div class="input-group">
            <button type="button" class="btn btn-primary" onclick="sendMessage()">Primary</button>
        </div>
        <script src="../models/ChatManager.js"></script>
    </div>


<?php require_once('template/footer.phtml'); ?>