<?php
 require_once "views/template/header.phtml";
 require_once "createPost.php";
?>
<div class="login-form animations appear"id="createPostForm">
    <form action="CreatePost.php" method="post" id="createPostForm" enctype="multipart/form-data">
        <h2 class="text-center">Create Post</h2>
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Post Title" required="required" name="postTitle" maxlength="25">
        </div>
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Category" required="required" name="postCategoryName" maxlength="25">
        </div>
        <div class="container form-group">
            <form>
                <div class="form-group">
                    <label for="comment">Comment:</label>
                    <textarea class="form-control" rows="5" id="comment" name="postContent" maxlength="250" ></textarea>
                </div>
            </form>
<!--            File upload field               -->
            <div class="form-group">
                <input type="file" name="fileToUpload" id="fileToUpload" required="required">
            </div>
<!--            Create post button              -->
            <div class="form-group">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit" name="createPostButton" id="createPostButton">Create Post</button>
                <br>
            </div>
        </div>
    </form>
<!-- If everything is successful -->
    <?php
    if ($view->postError == "none") {
        ?>
        <div class="alert alert-success text-center animations bounceIn" id="errorMessage" role="alert">
            Post has been uploaded!
        </div>
    <?php } ?>
<!-- If the file is already in the database -->
    <?php
    if ($view->postError == "fileExists") {
        ?>
        <div class="alert alert-danger text-center animations bounceIn id="errorMessage" role="alert">
            The image of this post already exists!
        </div>
    <?php } ?>
<!-- If the file is too big -->
    <?php
    if ($view->postError == "fileTooBig") {
        ?>
        <div class="alert alert-danger text-center animations bounceIn" id="errorMessage" role="alert">
            The image is too big!
        </div>
    <?php } ?>
<!-- If the file type is incorrect -->
    <?php
    if ($view->postError == "wrongFileType") {
        ?>
        <div class="alert alert-danger text-center animations bounceIn" id="errorMessage" role="alert">
            Wrong image format type!
        </div>
    <?php } ?>
<!-- If the title of the post is inappropriate -->
    <?php
    if ($view->postError == "wrongTitle") {
        ?>
        <div class="alert alert-danger text-center animations bounceIn" id="errorMessage" role="alert">
            Inappropriate title!
        </div>
    <?php } ?>
<!-- If the category name is inappropriate -->
    <?php
    if ($view->postError == "wrongCategory") {
        ?>
        <div class="alert alert-danger text-center animations bounceIn" id="errorMessage" role="alert">
            Inappropriate category name!
        </div>
    <?php } ?>
<!-- If the post content does not match specified parameters -->
    <?php
    if ($view->postError == "wrongContent") {
        ?>
        <div class="alert alert-danger text-center animations bounceIn" id="errorMessage" role="alert">
            Inappropriate post content!
        </div>
    <?php } ?>
</div>
<?php
require_once "views/template/footer.phtml";
?>