<!-- Footer -->
<footer class="page-footer font-small" id="pageFooter">
    <!-- Grid row -->
    <div class="row d-flex text-center justify-content-center mb-md-0 mb-4">
        <!-- Grid column -->
        <div class="col-md-8 col-12 mt-5">
            <div>
                <p id="logoBottomText">This is a forum about nature, you can post stunning nature images, fun facts
                    about different living creatures, and how you contributed to natures health.</p>
            </div>
        </div>
    </div>
    </div>
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">©2019 Copyright:
        <a href="index.php"> FORUM_NATURA</a>
    </div>
    <!-- Copyright -->
</footer>
</body>
</html>