<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" width="device-width">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <!--    Link to CSS files -->
    <link rel="stylesheet" href="../css/style.css">
    <link rel="stylesheet" href="../css/animations.css">
    <!--    This is used for all of the icons -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css">
    <!--    Javascript  -->
    <script src="js/script.js"></script>
    <title><?php echo $view->pageTitle; ?></title>
</head>
<body>
<header>
<!--    Website Logo at the top of the page   -->
    <div class="animations deconstructed">
        <div>F🌍RUM_NATURA</div>
        <div>F🌍RUM_NATURA</div>
        <div>F🌍RUM_NATURA</div>
        <div>F🌍RUM_NATURA</div>
        <div>F🌍RUM_NATURA</div>
    </div>
<!-- This is the top navigation bar code -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light" id="navBar">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- All of the other stuff in the nav bar -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <!--                Home button                 -->
                <li class="nav-item active" id="navBarItem">
                    <a class="nav-link" href="index.php">Home <span class="sr-only">(current)</span></a>
                </li>
                <?php
                if (isset($_SESSION['username'])) {
                    ?>
                    <!--            Create Post            -->
                    <li class="nav-item active" id="navBarItem">
                        <a class="nav-link" href="CreatePost.php">Create Post<span class="sr-only">(current)</span></a>
                    </li>
                    <!--            Watch List           -->
                    <li class="nav-item active" id="navBarItem">
                        <a class="nav-link" href="watchList.php">Watch List<span class="sr-only">(current)</span></a>
                    </li>
                    <?php
                }
                ?>
                <!--        Contact button     -->
                <li class="nav-item active" id="navBarItem">
                    <a class="nav-link" href="#">Contact <span class="sr-only">(current)</span></a>
                </li>
                <!--                About                   -->
                <li class="nav-item active" id="navBarItem">
                    <a class="nav-link" href="#">About <span class="sr-only">(current)</span></a>
                </li>
            </ul>
            <?php
            if (!isset($_SESSION['username'])) {
                ?>
                <!--            Login button            -->
                <form class="form-inline my-2 my-lg-0" action="login.php" method="post" id="navBarItem">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Login</button>
                </form>
                <?php
            } else {
                ?>
                <!--                Shows the name of the user who has logged in                -->
                <label class="navbar-brand">Logged in as <strong><?php echo $_SESSION['username'] ?></strong></label>
                <form class="form-inline my-2 my-lg-0" method="post">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit" name="logoutButton">Logout
                    </button>
                </form>
                <?php
            }
            ?>
        </div>
    </nav>
</header>